apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - "groups":
      - "system:bootstrappers"
      - "system:nodes"
      "rolearn": "arn:aws:iam::522838200446:role/cloudgrv-dev-eks-workers"
      "username": "system:node:{{EC2PrivateDNSName}}"



